export const products = [
  {
  id: 1,
  name: 'Apple Pencil (2nd Generation)',
  price: 23.5,
  description: 'Apple Pencil (2nd generation) brings your work to life. With imperceptible lag, pixel-perfect precision, and tilt and pressure sensitivity, it transforms into your favorite creative instrument, your paint brush, your charcoal, or your pencil.',
  url: 'https://www.amazon.com/Apple-MU8F2AM-A-Pencil-Generation/dp/B07K1WWBJK/ref=lp_16225007011_1_1',
  image: 'https://m.media-amazon.com/images/I/41S3MKU9TjL._AC_SX679_.jpg',
  rating: 'https://toppng.com/uploads/preview/five-star-rating-11549726812abjskp8qz8.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  {
  id: 2,
  name:'Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PlayStation, & Xbox - 1-Year Rescue Service (STGX2000400)',
  price: 59.99,
  description: 'Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop',
  url: 'https://www.amazon.com/Seagate-Portable-External-Hard-Drive/dp/B07CRG94G3/ref=lp_16225007011_1_2?th=1',
  image: 'https://m.media-amazon.com/images/I/81tjLksKixL._AC_SX679_.jpg',
  image2: 'https://m.media-amazon.com/images/I/91QqR55XhQL._AC_SX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/918-cGeMaRL._AC_SX679_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Star_rating_4_of_5.png',
  show: true,
  likes: 0,
  categoryId: 2
  },
  {
  id: 3,
  name: 'Logitech MK270 Wireless Keyboard and Mouse Combo for Windows, 2.4 GHz Wireless, Compact Mouse, 8 Multimedia and Shortcut Keys, 2-Year Battery Life, for PC, Laptop',
  price: 24.64,
  description: 'Easy to Use: This wireless keyboard and mouse combo features 8 multimedia hotkeys for instant access to the Internet, email, play/pause, and volume so you can easily check out your favorite sites',
  url: 'https://www.amazon.com/Logitech-MK270-Wireless-Keyboard-Mouse/dp/B079JLY5M5/ref=lp_16225007011_1_6',
  image: 'https://m.media-amazon.com/images/I/61pUul1oDlL._AC_SX679_.jpg',
  image2: 'https://m.media-amazon.com/images/I/71X4aSJLm5L._AC_SX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/61RWEZEg58L._AC_SX679_.jpg',
  rating: 'https://toppng.com/uploads/preview/five-star-rating-11549726812abjskp8qz8.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  {
  id: 4,
  name: 'Android 10, 10 inch Pritom Kids Tablet, Parental Control, 6000mAh, 3G Phone Tablet, Quad Core Processor',
  price: '108.99',
  description: '[Kids Tablet with Parent Control App] - With Pritom Kids(Pre-installed App for kids), it will be quite convenient for parents while benefit for kids to use Pritom K10 Tablet.',
  url: 'https://www.amazon.com/Android-Parental-Control-Processor-Kids-Tablet/dp/B09NJJ8JS2/ref=sr_1_1_sspa?qid=1646591202&rnid=16225007011&s=computers-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyUjUyOVhISE5XQzNFJmVuY3J5cHRlZElkPUEwNjAzNjcyMUNaVlQ4Qlo4NVdWRiZlbmNyeXB0ZWRBZElkPUEwNTE3MjE1MzcyRk9KODJLSDBHUiZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
  image: 'https://m.media-amazon.com/images/I/71pOdB6u9CL._AC_SX569_.jpg',
  image2: 'https://m.media-amazon.com/images/I/71G0f1JkIjL._AC_SY450_.jpg',
  image3: 'https://m.media-amazon.com/images/I/71M04VBeT9L._AC_SY450_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Star_rating_4_of_5.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  {
  id: 5,
  name: 'Samsung Tab A7 Lite 8.7" Gray 32GB (SM-T220NZAAXAR)',
  price: '949.99',
  description: 'STURDY FRAME FOR LASTING PROTECTION: Galaxy Tab A7 Lite features an upgraded metal frame that helps protect against everyday hiccups',
  url: 'https://www.amazon.com/Samsung-Lite-Gray-32GB-SM-T220NZAAXAR/dp/B094Q89NKH/ref=sr_1_9?qid=1646591202&rnid=16225007011&s=computers-intl-ship&sr=1-9&th=1',
  image: 'https://m.media-amazon.com/images/I/819hAP4xoGS._AC_SX679_.jpg',
  image2: 'https://m.media-amazon.com/images/I/61coIkTZ84S._AC_SX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/71GletxnoxS._AC_SX679_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Star_rating_4_of_5.png',
  show: true,
  likes: 0,
  categoryId: 2
  },
  {
  id: 6,
  name: 'Sax Manila Drawing Paper, 40 Lb., 9 x 12 Inches, Pack of 500',
  price: '13.99',
  description: 'Strong, durable construction for a variety of uses',
  url: 'https://www.amazon.com/Sax-Manila-Drawing-Paper-Inches/dp/B003U6QF4G/ref=sr_1_1_sspa?qid=1646591561&s=arts-crafts-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzQ0JLRjlFQldXMllCJmVuY3J5cHRlZElkPUEwOTE4NDU4MVBJUE9QWEdQU0tMRiZlbmNyeXB0ZWRBZElkPUEwODAxNTcxMUlJSlRXSFBISFE3NCZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
  image: 'https://m.media-amazon.com/images/I/61bns7wvczL._SX522_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Star_rating_4_of_5.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  {
  id: 7,
  name: 'MEEDEN 215-Piece Mega Wooden Box Art Set, Deluxe Painting & Drawing Kit with All Paint Supplies for Kids, Beginners and Adults',
  price: '23.99',
  description: 'VERSATILE ART SET: This deluxe art set contains a remarkable 215 pieces -60 crayons, 24 oil pastels, 24 colored pencils, 24 watercolor cakes, 8 acrylic paints',
  url: 'https://www.amazon.com/MEEDEN-99-Piece-Watercolor-Additional-Everything/dp/B07ZRH7PZ9/ref=sr_1_14_sspa?qid=1646591682&s=arts-crafts-intl-ship&sr=1-14-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExTDJQSlIyVEU1QTI1JmVuY3J5cHRlZElkPUEwMjIzNDIyM0JUN1VDMEk1TEJJRiZlbmNyeXB0ZWRBZElkPUEwMzU0MjYxM1BXMVJHUEQ2UFM5WCZ3aWRnZXROYW1lPXNwX210Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
  image: 'https://m.media-amazon.com/images/I/81d6e4Mp+YL._AC_SX679_.jpg',
  image2: 'https://m.media-amazon.com/images/I/811idQESFSL._AC_SX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/8157I3InaHL._AC_SX679_.jpg',
  rating: 'https://toppng.com/uploads/preview/five-star-rating-11549726812abjskp8qz8.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  {
  id: 8,
  name: 'FIBARO The Button Z-Wave Plus Scene Controller On-Off Trigger, FGPB-101-3, Red',
  price: '49.93',
  description: 'Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter',
  url: 'https://www.amazon.com/Fibaro-FGPB-101-3-US-Button-Controller/dp/B01M9JQJZZ/ref=sr_1_11?qid=1646591934&sr=8-11&srs=21217035011',
  image: 'https://m.media-amazon.com/images/I/51BtSQhVkCL._AC_SY450_.jpg',
  image2: 'https://m.media-amazon.com/images/I/711WzRKTrSL._AC_SY450_.jpg',
  image3: 'https://m.media-amazon.com/images/I/81OTFIWMVxL._AC_SX450_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/3_stars.svg/1024px-3_stars.svg.png',
  show: true,
  likes: 0,
  categoryId: 3
  },
  {
  id: 9,
  name: 'Anne Klein Womens Genuine Diamond Dial Open Bangle Watch',
  price: '46.06',
  description: 'Split bangle with jewelry-clasp closure',
  url: 'https://www.amazon.com/Anne-Klein-AK-2626RGRG-Diamond-Accented/dp/B01H5CQFPO/ref=sr_1_5?qid=1646592106&s=fashion-womens-intl-ship&sr=1-5&th=1',
  image: 'https://m.media-amazon.com/images/I/81iAfA+bwbL._AC_UY879_.jpg',
  image2: 'https://m.media-amazon.com/images/I/61PgCoEcxEL._AC_UX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/71IsN+R+FJL._AC_UY741_.jpg',
  rating: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Star_rating_4_of_5.png',
  show: true,
  likes: 0,
  categoryId: 2
  },
  {
  id: 10,
  name: 'Timex Womens Indiglo Easy Reader Quartz Analog Leather Strap Watch with Date Feature',
  price: '32.90',
  description: 'Silver-tone 25 millimeter brass case with mineral glass crystal',
  url: 'https://www.amazon.com/Timex-T2H331-Indiglo-Leather-Silver-Tone/dp/B000AYW0M2/ref=sr_1_17?qid=1646592393&s=fashion-womens-intl-ship&sr=1-17&th=1',
  image: 'https://m.media-amazon.com/images/I/81JKr2K7TtL._AC_UY879_.jpg',
  image2: 'https://m.media-amazon.com/images/I/61IxrZrqNAL._AC_UX679_.jpg',
  image3: 'https://m.media-amazon.com/images/I/6101w4AheML._AC_UX679_.jpg',
  rating: 'https://toppng.com/uploads/preview/five-star-rating-11549726812abjskp8qz8.png',
  show: true,
  likes: 0,
  categoryId: 1
  },
  ];